Various fixes and additions
Hack-with-Github/Awesome-Hacking pull request #144
Opened 2023-01-09 11:12 UTC by projectdp

- Fixed markdown issues per markdown linter.
- Moved awesome repositories into the correct section and moved non-awesome repositories to the correct section.
- Sorted lists.
- Added a variety of repositories.
- Added Track Awesome List.
- Added Awesome button.
- Minor fixes to contributions, added self to contributions.

2023-01-09 11:15 UTC, cat998 commented
已收到！

2023-02-08 13:31 UTC, Fjrhamzah277 commented
saya tertarik mempelajari membuat applikasi peretasan Android dengan cara umpan dengan Link. apakah ada yang bisa membantu?

2023-02-13 21:47 UTC, Caoxokhuyen approved these changes
def fibonacci(n)
  return n if ( 0..1 ).include? n
  (fibonacci(n - 1) + fibonacci(n - 2)) #recursive calls
end

2023-03-30 21:54 UTC, Ethical1and0 commented
Great.

2023-04-05 06:48 UTC, LancealotSeven commented
///////AA:A////HUT DOWN THE BUG////AA:A////AL////AA:G////O ////AA:A////HUT DOWN THY HACKER///////LL:L///////FROM TAKING DOWN YOUR FIREWALL///////

2023-04-20 01:44 UTC, Pawancyber commented
Nice.

2023-04-20 01:44 UTC, cat998 commented
已收到！

2023-06-03 05:11 UTC, IAmBlackHacker commented
❤️

2023-06-04 17:11 UTC, 9miuz commented
Thanks

On Sat, Jun 3, 2023, 6:15 AM Werths ***@***.***> wrote:

> ❤️
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Hack-with-Github/Awesome-Hacking/pull/144#issuecomment-1574661642>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6LVU55IITT4YHS525QFNADXJLB75ANCNFSM6AAAAAATVJRQQU>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-06-15 09:12 UTC, ohhruna approved these changes

2024-04-08 18:08 UTC, Leyder2007 requested changes
Viperbleis

2024-04-13 12:09 UTC, Chan9390 commented
@projectdp This is cool. Can you please remove the badges?

2024-04-13 16:35 UTC, Kishore007raj commented
cool!!

2024-04-14 08:30 UTC, qwerrttz234 approved these changes

2024-05-24 09:08 UTC, NazarTovstyha1 approved these changes

2024-05-26 02:56 UTC, Lilitmrz reviewed
9

2024-05-26 02:57 UTC, Lilitmrz requested changes
H

2024-06-04 07:52 UTC, Leyder9537thd requested changes

2024-06-04 07:52 UTC, Leyder9537thd commented on contributing.md
>  - [Derick Thomson](https://www.facebook.com/derick.thomson) (Image)
] ( https://github.com/infoslack/awesome-web-hacking )

2024-06-09 03:46 UTC, Femida666 approved these changes

2024-06-14 01:19 UTC, devilish66694 approved these changes
Good

2024-06-14 01:22 UTC, devilish66694 approved these changes

2024-06-20 11:42 UTC, llkkkklllllls approved these changes

2024-06-20 11:42 UTC, llkkkklllllls approved these changes

2024-06-20 11:43 UTC, llkkkklllllls approved these changes

2024-06-20 12:39 UTC, llkkkklllllls approved these changes

2024-06-20 12:39 UTC, llkkkklllllls commented on contributing.md
> -- [Alan Chang](https://github.com/tcode2k16)
(@IAmBlackHacker _**_)

2024-06-21 00:05 UTC, devilish66694 approved these changes

2024-06-21 00:05 UTC, devilish66694 commented on contributing.md
> -- [Alan Chang](https://github.com/tcode2k16)
> (@IAmBlackHacker _**_)

Verified

2024-06-21 00:06 UTC, devilish66694 approved these changes

2024-06-21 00:06 UTC, devilish66694 commented on contributing.md
>  - [Derick Thomson](https://www.facebook.com/derick.thomson) (Image)
> ] ( https://github.com/infoslack/awesome-web-hacking )

2024-06-21 00:07 UTC, devilish66694 approved these changes

2024-06-27 04:06 UTC, w1s3one805 approved these changes

2024-06-27 04:59 UTC, Fjrhamzah277 commented
I have not received

Pada Kam, 27 Jun 2024 12.06, w1s3one805 ***@***.***> menulis:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Hack-with-Github/Awesome-Hacking/pull/144#pullrequestreview-2144125252>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5YDJEOK6JZNK2QTWNP72YTZJOFVZAVCNFSM6AAAAAATVJRQQWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNBUGEZDKMRVGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-07-23 16:16 UTC, IAmBlackHacker approved these changes

2024-08-22 10:37 UTC, closed without merging

2024-08-22 10:38 UTC, Chan9390 commented
There are quite a few conflicts with existing state. I'm closing the PR for now. Feel free to create new one :)