Add crypto_pkg
Hack-with-Github/Awesome-Hacking pull request #162
Opened 2024-06-10 20:22 UTC by programmingAthlete

add crypto_pkg cryptanalysis package

2024-06-14 01:22 UTC, devilish66694 approved these changes

2024-06-16 04:52 UTC, Astrotony approved these changes

2024-06-16 09:55 UTC, MarkjhuneBahian requested changes
Iyotabe

2024-06-17 08:20 UTC, alfredmang approved these changes

2024-06-18 02:06 UTC, merlinwizzard commented
{[Remove-\-Damon-\Reinstall-\Main-Repositiory-\-]}{[Run-Prg]}

2024-06-25 01:54 UTC, Kuntree12 approved these changes

2024-06-25 12:06 UTC, alfredmang reviewed
Fake online login

2024-06-25 12:06 UTC, alfredmang requested changes
Deny access

2024-06-25 21:54 UTC, programmingAthlete commented
> Fake online login

@alfredmang, what do you mean?

2024-06-26 11:30 UTC, alfredmang approved these changes

2024-06-26 11:34 UTC, alfredmang approved these changes
add crypto_pkg cryptanalysis package

2024-07-01 04:07 UTC, Kuntree12 approved these changes

2024-07-19 03:17 UTC, Jitendrapande20 approved these changes

2024-07-27 06:59 UTC, Amaryasir9 reviewed
Good

2024-07-27 09:33 UTC, Katka1983 approved these changes

2024-07-30 11:35 UTC, programmingAthlete commented
Need the approval of someone with writing access. If you have writing access and you agree with this PR, please approve it

2024-07-31 21:24 UTC, devilish66694 approved these changes

2024-08-10 11:50 UTC, Emmanuel001v commented
Nice

2024-08-10 13:43 UTC, devilish66694 approved these changes

2024-08-10 13:44 UTC, devilish66694 approved these changes

2024-08-21 18:32 UTC, Moneyman60 approved these changes

2024-08-21 18:34 UTC, Moneyman60 approved these changes

2024-08-21 18:36 UTC, Moneyman60 requested changes

2024-08-21 18:36 UTC, Moneyman60 commented on README.md
> +[CryptoPkg](https://github.com/programmingAthlete/crypto_pkg) | Cryptanalysis package containing attacks to modified versions of some known symmetric key ciphers and correlation power analysis attack
Yes

2024-08-22 10:35 UTC, closed without merging